name: CI - deps check (npm)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (npm)
        run: npm ci --prefer-offline --no-audit --no-fund || npm install

      - name: Audit dependencies (report)
        run: |
          set -o pipefail
          npm audit --json > audit.json || true
          cat audit.json || true

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit.json

      - name: List top-level deps
        run: npm ls --depth=0 || true